name: webdav_client
description: A simple WebDAV client that supports some common methods.

version: 1.2.1
homepage: https://github.com/flymzero/webdav_client

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  dio: ^5.3.2
  xml: ^6.3.0
  convert: ^3.1.1

dev_dependencies:
  test: '>=1.0.0 <2.0.0'
